--Display which groups an audit rule applies to as well as exception level, message etc 

AUDL.NAME AS [Audit Rule],

   AUD.EXPRESSION_KEY AS [Audit Key],

   COALESCE(ITE.LI_CODE,'Global') AS [Group Code],

   XCT.EXCEPTION_CODE AS [Exception Code],

   XCTL.MESSAGE AS [Exception Message],

   XCT.SEVERITY_LEVEL AS [Exception Level],

   CASE ACT.EXCEPTION_VISIBILITY

      WHEN 1 THEN 'Traveler, Approver and Expense Processor'

      WHEN 2 THEN 'Approver and Expense Processor'

      WHEN 3 THEN 'Expense Processor' END AS [Exception Visibility]

FROM CT_AUDIT_RULE AUD

   INNER JOIN CT_AUDIT_RULE_LANG AUDL ON AUDL.EXPRESSION_KEY = AUD.EXPRESSION_KEY

   INNER JOIN CT_RULE_ACTION ACT ON ACT.EXPRESSION_KEY = AUDL.EXPRESSION_KEY

   INNER JOIN CT_EXCEPTION XCT ON XCT.XCT_KEY = ACT.XCT_KEY

   INNER JOIN CT_EXCEPTION_LANG XCTL ON XCTL.XCT_KEY = XCT.XCT_KEY

     AND XCTL.LANG_CODE = AUDL.LANG_CODE

   INNER JOIN CT_CONFIG_HIER_NODE_MAP MAP ON MAP.KEY_VALUE = AUD.EXPRESSION_KEY

     AND MAP.TABLE_REF = 'CT_AUDIT_RULE'

   INNER JOIN CT_HIERARCHY_NODE NOD ON NOD.HIER_NODE_KEY = MAP.HIER_NODE_KEY

   LEFT JOIN CT_LIST_ITEM_MAP ITE ON ITE.LI_KEY = NOD.SEGMENT_1

WHERE AUD.IS_ACTIVE = 'Y'

   AND MAP.IS_ACTIVE = 'Y' -- Applied to the Group

   AND AUDL.LANG_CODE = 'en'

   --AND XCT.EXCEPTION_CODE = 'EXCEPTION CODE'

   --AND AUDL.NAME = 'AUDIT RULE NAME' ORDER BY 1, 3
