-- Replace XXX with Outtask Company ID 

SELECT * FROM OUTTASK_USER OU JOIN OUTTASK_USER_SET_HAS_ROLES OUHR ON OU.SET_ID = OUHR.SET_ID JOIN CODE_MODULE_ROLES CMR ON CMR.MODULE_ROLE_CODE = OUHR.MODULE_ROLE_CODE AND ROLE_NAME_EN_US = 'AUTHORIZED SUPPORT CONTACT' AND OU.COMPANY_ID = 'XXX' 
