-- Set 'Travel Databases' to 'Outtask' 

-- Replace XXX with email address 

SELECT U.FIRST_NAME, U.LAST_NAME, U.COMPANY_EMPLOYEE_ID, E.EMAIL_ADDRESS, C.COMPANY_NAME, C.ENTITY_ID FROM OUTTASK_USER U WITH (NOLOCK) JOIN OUTTASK_COMPANY C ON U.COMPANY_ID = C.COMPANY_ID JOIN OUTTASK_USER_VERIFIED_EMAIL E ON U.USER_ID = E.USER_ID AND E.EMAIL_ADDRESS = 'XXX'  
