-- Replace XXX with List Name 

SELECT * FROM CT_LIST_ITEM_LANG AS LANG  

JOIN CT_LIST_ITEM AS ITEM ON LANG.LI_KEY=ITEM.LI_KEY  

WHERE LC_KEY IN (SELECT LC_KEY FROM CT_LIST_CATEGORY_LANG WHERE NAME = 'XXX')  

AND LANG_CODE = 'en' AND ITEM.IS_DELETED = 'N' 
