-- Replace XXX with Users LOGIN_ID 

SELECT MAP.EMP_KEY,MAP.HIER_NODE_KEY, LANG.ROLE_CODE, LANG.NAME FROM CT_EMPLOYEE_ROLE_MAP AS MAP JOIN CT_ROLE_LANG AS LANG ON MAP.ROLE_CODE = LANG.ROLE_CODE WHERE EMP_KEY IN (SELECT EMP_KEY FROM CT_EMPLOYEE WHERE LOGIN_ID = 'XXX') AND LANG. LANG_CODE = 'en' 
