-- Replace XXX with the Form Field Lable 

SELECT * FROM CT_FORM_FIELD_LANG FFL JOIN CT_FORM_FIELD FF ON FFL.FF_KEY=FF.FF_KEY JOIN CT_FORM F ON FF.FORM_KEY=F.FORM_KEY JOIN CT_FORM_LANG FL ON F.FORM_KEY=FL.FORM_KEY WHERE FFL.LABEL = 'XXX' AND FFL.LANG_CODE = 'en' AND FL.LANG_CODE = 'en' 
