--Run in DB Select
--Replace XXX with Ledger name and run 

SELECT LEDLANG.NAME AS 'Ledger Name', 
  EXP.LANG.NAME AS 'Expense Type', 
  MAP.ACCOUNT_CODE AS 'Account Code'  
FROM CT_ACCOUNT_NODE AS NODE  
  JOIN CT_ACCT_NODE_EXP_TYPE_MAP AS MAP ON NODE.NODE_KEY = MAP.NODE_KEY 
  JOIN CT_LEDGER AS LED ON NODE.LEDGER_KEY = LED.LEDGER_KEY 
  JOIN  CT_LEDGER_LANG AS LEDLANG ON LEDLANG.LEDGER_KEY = LED.LEDGER_KEY 
  JOIN CT_EXPENSE_TYPE_LANG AS EXPLANG ON EXPLANG.EXP_KEY = MAP.EXP_KEY 
  AND LEDLANG.LANG_CODE = 'en' AND EXPLANG.LANG_CODE = 'en' AND MAP.ACCT_CODE_TYPE = 1 
WHERE LEDLANG.NAME = 'XXX'  
